-- Supabase Database Schema for Bot Proxy System
-- Run this SQL in your Supabase SQL Editor to set up the database

-- Create proxy_configs table
CREATE TABLE IF NOT EXISTS proxy_configs (
  id TEXT PRIMARY KEY,
  real_url TEXT NOT NULL,
  bot_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- Create index on created_at for faster queries
CREATE INDEX IF NOT EXISTS idx_proxy_configs_created_at ON proxy_configs(created_at DESC);

-- Enable Row Level Security (RLS)
ALTER TABLE proxy_configs ENABLE ROW LEVEL SECURITY;

-- Create policy to allow all operations (adjust based on your security needs)
-- For public access (anonymous users can create and read proxy configs)
CREATE POLICY "Allow public read access" ON proxy_configs
  FOR SELECT
  USING (true);

CREATE POLICY "Allow public insert access" ON proxy_configs
  FOR INSERT
  WITH CHECK (true);

-- Optional: If you want to add delete/update policies in the future
-- CREATE POLICY "Allow public update access" ON proxy_configs
--   FOR UPDATE
--   USING (true);

-- CREATE POLICY "Allow public delete access" ON proxy_configs
--   FOR DELETE
--   USING (true);

-- Add comments for documentation
COMMENT ON TABLE proxy_configs IS 'Stores proxy configurations for bot detection and redirection';
COMMENT ON COLUMN proxy_configs.id IS 'Unique proxy identifier generated by nanoid';
COMMENT ON COLUMN proxy_configs.real_url IS 'URL where legitimate users are redirected';
COMMENT ON COLUMN proxy_configs.bot_url IS 'URL where detected bots are redirected';
COMMENT ON COLUMN proxy_configs.created_at IS 'Timestamp when the proxy configuration was created';
